version: '3'
services:
  edge_booking_main:
    container_name: edge_booking_main
    restart: on-failure:5
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    volumes:
      - ./available:/home/edge_booking/available
      - ./log:/home/edge_booking/log
      - ./screenshots:/home/edge_booking/screenshots
    environment:
      ENVIRONMENT: prod
    network_mode: host
    depends_on:
      edge_booking_web_driver:
        condition: service_started
    secrets:
      - booking_config
    logging:
      options:
        max-size: 50m

  edge_booking_web_driver:
    container_name: edge_booking_driver
    image: seleniarm/standalone-firefox:120.0
    network_mode: host
    shm_size: 2g
    logging:
      options:
        max-size: 50m

secrets:
  booking_config:
    file: config/config.ini
