version: '3'
services:
  edge_booking_main:
    container_name: edge_booking_main
    restart: unless-stopped
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    volumes:
      - ./available:/home/edge_booking/available
    env_file:
      - .env
    network_mode: host
    depends_on:
      edge_booking_web_driver:
        condition: service_started
    logging:
      options:
        max-size: 50m

  edge_booking_web_driver:
    container_name: edge_booking_driver
    image: seleniarm/standalone-firefox:120.0
    network_mode: host
    shm_size: 2g
    logging:
      options:
        max-size: 50m
