services:
  edge_booking_main:
    container_name: edge_booking_main
    restart: on-failure:5
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    volumes:
      - ./available:/home/edge_booking/available
      - ./log:/home/edge_booking/log
      - ./screenshots:/home/edge_booking/screenshots
    depends_on:
      edge_booking_web_driver:
        condition: service_started
    logging:
      options:
        max-size: 50m

  edge_booking_web_driver:
    container_name: edge_booking_driver
    image: seleniarm/standalone-firefox:120.0
    ports:
      - "4444:4444"
    shm_size: 2g
    logging:
      options:
        max-size: 50m
